### ISSUE TITLE
Are there any plans on updating this to work with Wordpress again?

### ISSUE THREAD

**Issue by anointed** [kaltura/all-in-one-video-pack.wordpress#11]
Topic pretty much says it all. 
With WordPress 3.9 there are a huge amount of nice changes regarding media, yet I see no way to get the Kaltura WP plugin to work with wp now.

*Mostly curious if Kaltura has given up on WordPress players as it has been a very very long time since the last update.

**Comment by Roycohen** [comment]
@anointed, anything new?

**Comment by tvsmurphman** [comment]
Has anyone figured out how to add a search function to the Video All in One Kaltura window when adding videos to WP posts?  And how to make the window bigger?  
![allinonevideowindowwordpress](https://cloud.githubusercontent.com/assets/8581327/9022733/cfaa7d68-384e-11e5-8070-4b55ab023d46.png)
