### ISSUE TITLE
Upgrade Kaltura client library to latest

### ISSUE THREAD

**Issue by rkreich** [kaltura/all-in-one-video-pack.wordpress#59]
Created out of https://github.com/kaltura/all-in-one-video-pack.wordpress/pull/56

Kaltura client library used by WordPress plugin needs to be updated to latest version.
When generating new `PhpZendClientGenerator` using the following config https://github.com/kaltura/all-in-one-video-pack.wordpress/blob/master/lib/Kaltura/client-generation-readme.txt and the latest code of `clients-generator` (https://github.com/kaltura/clients-generator), it produces huge diff.

A few issues:
* Empty plugins added.
* [`KalturaListResponse`](https://github.com/kaltura/clients-generator/blob/b4477c6a6be47dd97776b5fecb20d3a557892bcb/lib/ClientGeneratorFromXml.php#L232) causes all `*ListResponse` types to be added.
* [`KalturaRequestConfiguration`](https://github.com/kaltura/clients-generator/blob/b4477c6a6be47dd97776b5fecb20d3a557892bcb/lib/ClientGeneratorFromXml.php#L231) references `KalturaDetachedResponseProfile` which adds all types inherited by `KalturaRelatedFilter` (`KalturaDetachedResponseProfile::filter`).

Client lib code needs to stay minimal to have the plugin compatible with VIP.

**Comment by rkreich** [comment]
@jessp01 - I've added the needed options to client-generator repo (see https://github.com/kaltura/clients-generator/pull/170), to allow generating new API client libraries for WordPress.
Can you create a github repo for it? As discussed on https://github.com/kaltura/all-in-one-video-pack.wordpress/pull/56. 
(`config/generator.ini` was updated).
Thanks

**Comment by jessp01** [comment]
Hi @rkreich, sure. As soon as @tan-tan-kanarek merges https://github.com/kaltura/clients-generator/pull/170/files. Also, add wordpress here: https://github.com/kaltura/clients-generator/blob/Mercury-13.2.0/config/generator.all.ini

**Comment by jessp01** [comment]
Done, see https://github.com/kaltura/KalturaGeneratedAPIClientsWordpress

**Comment by rkreich** [comment]
Thanks.
I've updated the client library on https://github.com/kaltura/all-in-one-video-pack.wordpress/pull/74
Closing issue.
